name: Deploy Coverage Report

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write 

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Download JaCoCo report artifact
      uses: actions/download-artifact@v4
      with:
        name: jacoco-report
        path: ./target/site/jacoco

    - name: Deploy JaCoCo report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/jacoco